put:
  operationId: ResetServerConfig
  tags:
    - servers
  summary: Reset server configuration to default state
  security:
    - bearerAuth: []
  parameters:
    - in: path
      name: sid
      required: true
      schema:
        type: integer
  responses:
    '200':
      description: OK
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
    '500':
      $ref: ../components/responses/InternalServerError.yaml
